server:
  port: 8089

spring:
  application:
    name: provider-addOil
  datasource: # MySQL
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_todayoil?serverTimezone=UTC
    username: root
    password: 8019
  redis:  # Redis
    host: localhost
    port: 6379
    password:
  cloud:
    nacos:  # Nacos
      discovery:
        group: todayOil
        server-addr: localhost:8848
