server:
  port: 8766

spring:
  application:
    name: gateway-to
  redis:  # Redis
    host: ${prod.host}
    port: 6379
    password: r887GGYHJd
  cloud:
    nacos:  # Nacos
      discovery:
        group: todayOil
        server-addr: ${prod.host}:8848
    gateway: # Gateway
      routes:
      - id: api
        uri: lb://consumer
        predicates:
        - Path=/**

user:
  white-list:
  - /users/login
  - /users/enroll
  - /users/code
  - /oil-prices/
  - /favicon.ico

prod:
  host: 192.168.227.134