server:
  port: 8086

spring:
  application:
    name: provider-user
  datasource: # MySQL
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_todayoil?serverTimezone=UTC
    username: root
    password: 8019
  redis:  # Redis
    host: localhost
    port: 6379
    password:
  cloud:
    nacos:  # Nacos
      discovery:
        group: todayOil
        server-addr: localhost:8848

feign:  # Feign
  client:
    config:
      default:  # 设置默认超时时间（防止首次调用超时）
        connect-timeout: 5000
        read-timeout: 5000